### ISSUE TITLE
[BUG] Special Characters don't appear in Google Search

### ISSUE THREAD

**Issue by MaxTCodes** [alii/search#43]
Hi there,

I was messing around with the project, and I typed in `+`, and `#` it kept not appearing; I just double-checked, and it converted it from a URL encoded to a normal string, and the Google Search Engine doesn't like that... 

Thanks,
Max

**Comment by MaxTCodes** [comment]
I will compile a whole list and add it to the issue.

**Comment by MaxTCodes** [comment]
```
1. #
2. &
```
(characters that are used for query parameters) *I tried all the special characters and it came out to these are the ones that will cause issues*

**Comment by alii** [comment]
Looking into this now, thank you for letting me know

**Comment by alii** [comment]
Cool, resolved in 0f6404d – thank you for reporting this!

**Comment by Looskie** [comment]
![image](https://user-images.githubusercontent.com/50378828/134431642-2ae53f8c-db24-42fa-9e98-1e4f9a31ed62.png)
