### ISSUE TITLE
encoding of "+"

### ISSUE THREAD

**Issue by punctuations** [alii/search#55]
an issue was brought to my attention by @mrhappyma that the "+" does not get carried through to the search engine and is instead removed entirely.

I'll attach a video of said occurrence below (from @mrhappyma):
https://og.blurple.rip/38_AM.webm

source: https://github.com/punctuations/newtab/issues/13

**Comment by punctuations** [comment]
(when unescaped, sorry im a tad dumb, if this is redundant then its all good, sorry Alistair)

**Comment by punctuations** [comment]
I forgor (💀) to encode the query, mb

**Comment by alii** [comment]
@punctuations is this something I need to look at?

**Comment by punctuations** [comment]
no

**Comment by alii** [comment]
ok cool ty haha
