### ISSUE TITLE
Would really like a way to change the search engine

### ISSUE THREAD

**Issue by TheAwesomeCoder05** [alii/search#63]
I really don't like/use google. I prefer duckduckgo/others, hence it would be great if there was a way to change the preferences for this (for example an extension?).

**Comment by alii** [comment]
Yep that's already supported! You can pass `&engine=` in the query string as documented in the readme.

To use duckduckgo, use this URL instead
```
https://search.alistair.sh/?q=%s&engine=https:%2f%2fduckduckgo.com%2f%3fq={q}
```

**Comment by TheAwesomeCoder05** [comment]
Oh, thanks!
